### ISSUE TITLE
How to add options? tinymce.init({

### ISSUE THREAD

**Issue by noizo** [extras-evolution/tinymce4-for-modx-evo#15]
Hi.
How to modify default tinymce-modx-evo to include some additional parameters in **link** or any other plugin?

https://www.tinymce.com/docs/plugins/link/

I need to add **class** and **rel** option to Link window, but cant find where **tinymce.init({** value is.

Any help much appreciated.

**Comment by Deesen** [comment]
No problem its easy :-). 
- Copy a theme like `assets/plugins/tinymce4/theme.tinymce4.full.inc.php`
- Name it how you like, for example `assets/plugins/tinymce4/theme.tinymce4.noizo.inc.php`. It will appear in the "available themes" list in modx-configuration. So by next TinyMCE-update you won´t loose it.

Inside you will find 

```
$this->set('parameter', 'value', 'type');
```

So to add parameter [default_link_target](https://www.tinymce.com/docs/plugins/link/#default_link_target) you just have to copy parameter, value and type from TinyMCE-docs like

```
$this->set('default_link_target', '_blank', 'string');
```

and add it to your theme-file.

**Comment by Deesen** [comment]
P.S. If you don´t want to edit a theme you can add manual code into init({}) directly by using plugin-configuration "custom parameters" :

![customparam](https://cloud.githubusercontent.com/assets/8569221/13856456/96b60e38-ec75-11e5-9b1b-ffd23af16946.png)

But there were wrong names in the plugin-string left from development which is corrected with #16. The correct config-string should be

```
&styleFormats=Custom Style Formats;textarea;Title,cssClass|Title2,cssClass &customParams=Custom Parameters <b>(Be careful or leave empty!)</b>;textarea; &entityEncoding=Entity Encoding;list;named,numeric,raw;named &entities=Entities;text; &pathOptions=Path Options;list;Site config,Absolute path,Root relative,URL,No convert;Site config &resizing=Advanced Resizing;list;true,false;false &disabledButtons=Disabled Buttons;text; &webTheme=Web Theme;test;webuser &webPlugins=Web Plugins;text; &webButtons1=Web Buttons 1;text;bold italic underline strikethrough removeformat alignleft aligncenter alignright &webButtons2=Web Buttons 2;text;link unlink image undo redo &webButtons3=Web Buttons 3;text; &webButtons4=Web Buttons 4;text; &webAlign=Web Toolbar Alignment;list;ltr,rtl;ltr &width=Width;text;100% &height=Height;text;400px &inlineMode=<b>Inline-Mode</b>;list;enabled,disabled;disabled &inlineTheme=<b>Inline-Mode</b><br/>Theme;text;inline &editableClass=<b>Inline-Mode</b><br/>CSS-Class selector;text;editable &editableIds=<b>Inline-Mode</b><br/>Editable<br/>Modx-Phs->CSS-IDs<br/>(line-breaks allowed);textarea;longtitle->#modx_longtitle,content->#modx_content
```

**Comment by noizo** [comment]
I have a problem.
I did an update trough extras and manually after.
I cant access Settings in order to activate TinyMCE4 or any other html editor.

When i'm disabling plugin, settings are ok. But still no TinyMCE.
Is it possible that i have a conflict with CKeditor4 plugin?
I have deleted ckeditor from plugins page, still no luck.

When i'm enabling a plugin i cant access either file settings tab and file manager tab in setting.
![settings](https://cloud.githubusercontent.com/assets/1682474/13858575/b31a8482-ec98-11e5-9126-e3d45cb09611.jpg)

![tinymce](https://cloud.githubusercontent.com/assets/1682474/13858542/9112d88a-ec98-11e5-9512-17ab7a775bfe.jpg)
Everything seems to be just fine when plugin is disabled.
By the way, previous version worked just fine.

I also have tried to remove tinymce completely, then installed previous version, checked that its working, and then upgraded to latest. Still no luck.

**Comment by Deesen** [comment]
Pls check the source-code and scroll to the end.. is there any error-message? And which Modx-version?

**Comment by noizo** [comment]
![error](https://cloud.githubusercontent.com/assets/1682474/13859183/9f6e7ae4-ec9b-11e5-9b21-96418db0d7c5.jpg)

**Comment by Deesen** [comment]
I meant the HTML-code of the right big frame. There should be something like "File not found" ?

**Comment by noizo** [comment]
Nope, http://pastebin.com/BZuLftrb

**Comment by Deesen** [comment]
This is source-code of main-frame, but we need from right (left/right) frame. In Windows Firefox it is right mouse-click on right area -> actual frame -> show frame-source code

Maybe try
- adding this file to your installation: https://github.com/modxcms/evolution/blob/develop/assets/lib/class.modxRTEbridge.php to /assets/lib/class.modxRTEbridge.php

**Comment by noizo** [comment]
Awsome! It did the trick.
Thanks a lot!
Consider it fixed!
And i'm on 1.1RC-d7.1.6

**Comment by Deesen** [comment]
Nice :-)

**Comment by Deesen** [comment]
If no more errors pls close this issue, thanks.

**Comment by noizo** [comment]
One last thing as they say :)

I'm trying to add [rel](https://www.tinymce.com/docs/plugins/link/#rel_list) and [css](https://www.tinymce.com/docs/plugins/link/#link_class_list)

As for rel, i've added to theme
`$this->set('rel_list', 'rel', 'string', 'group1');`
`$this->set('rel_list', 'rel=group1', 'string',);`

![relempty](https://cloud.githubusercontent.com/assets/1682474/13860151/6a3a780a-eca0-11e5-81da-bd1b6c3ef009.jpg)
Where am i wrong? :)

**Comment by Deesen** [comment]
The TinyMCE-docs are wrong (object, not string). Try

```
$this->set('rel_list', "[
  {title: 'Lightbox', value: 'lightbox'},
  {title: 'Table of contents', value: 'toc'}
]", 'object');
```

**Comment by noizo** [comment]
Nope ): Tinymce window won't load

**Comment by Deesen** [comment]
Sry must always be " inside values instead of ' :

```
$this->set('rel_list', '[
  {title: "Lightbox", value: "lightbox"},
  {title: "Table of contents", value: "toc"}
]', 'object');
```

**Comment by noizo** [comment]
:+1: Now its workig!
**Thank You so much!**
